### ISSUE TITLE
Prettier v3 support

### ISSUE THREAD

**Issue by AlexAegis** [remcohaszing/remark-prettier#2]
Hi!

The long awaited Prettier V3 just released!

I'm getting some errors when running this plugin, as expected from the breaking changes..

```sh
error  TypeError: prettier.getFileInfo.sync is not a function
     at getOptions (file:///home/alex/git/@aa/js-tooling/node_modules/.pnpm/remark-prettier@2.0.0_prettier@3.0.0/node_modules/remark-prettier/index.js:21:47)
```

**Comment by remcohaszing** [comment]
I intend to support this, but it’s going to be semver major. A major update for unified is upcoming, so I’ll wait for that first.

**Comment by remcohaszing** [comment]
This project has been deprecated in favor of [`unified-consistency`](https://github.com/remcohaszing/unified-consistency) and [`unified-prettier`](https://github.com/remcohaszing/unified-prettier).
